### PR TITLE
Merge branch '2.3' of ezsystems/ezplatform-http-cache into 4.6

### PR DESCRIPTION
**Pull request by ezrobot**
Cross merge PR

### CODE REVIEW

**Comment by alongosz** [comment]
@glye you have conflicts here. 

Does github now generate those commits like "Merge commit from fork"? Keep in mind that commit like this won't be visible in auto-generated changelogs. However we can merge this PR adding `IBX-XXX:` prefix.

**Comment by glye** [comment]
@alongosz The "Merge commit from fork" is automatic, yes. The IBX is https://issues.ibexa.co/browse/IBX-9195 but that's not public anyway. We can make it public by changing it to non-security, but that's a kludge as well.

**Comment by glye** [comment]
@alongosz The form the merge should take is https://github.com/ibexa/http-cache-ghsa-fh7v-q458-7vmw/pull/1/files

**Comment by glye** [comment]
@alongosz Manual merge done, hope I didn't 🪛 it up.

**Review by ViniTou — APPROVED** [review]

**Review by alongosz — APPROVED** [review]

**Comment by alongosz** [comment]
> @alongosz The form the merge should take is https://github.com/ibexa/http-cache-ghsa-fh7v-q458-7vmw/pull/1/files

I don't have access to it @glye (:

**Comment by glye** [comment]
@alongosz Sorry, I removed already. But I'm pretty sure I got it right :)

**Review by konradoboza — APPROVED** [review]
I wasn't able to dig deep enough to have some further context on compression, but it feels like we are skipping it for some important content types (REST-related, JSON). I wonder if that has any repercussions on performance but I guess that wasn't checked, wasn't that?

**Comment by glye** [comment]
Yes, there can be a performance impact, but fixing it in other ways than turning of compression is a hard problem to solve, with security pitfalls. Ref. https://www.breachattack.com/
We can discuss it after release, agree to unblock release.

**Comment by konradoboza** [comment]
At least rate-limiting looks like potential low-hanging fruit, but this still only reduces the negative outcome. Thanks for the details @glye.

**Pull request merged**
